# Generated by Django 4.0.2 on 2022-02-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('rarity', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('priceChange', models.IntegerField()),
                ('dropPrice', models.IntegerField()),
                ('variantIssued', models.IntegerField()),
                ('totalIssued', models.IntegerField()),
                ('totalListed', models.IntegerField()),
            ],
        ),
    ]
