# Generated by Django 4.0.2 on 2022-02-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_comic_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='image',
            field=models.URLField(default='', verbose_name=''),
            preserve_default=False,
        ),
    ]
