# Generated by Django 4.0.2 on 2022-02-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_comic_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='image',
            field=models.URLField(verbose_name=' '),
        ),
    ]
