# Generated by Django 4.0.2 on 2022-02-27 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_comic_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='image',
            field=models.URLField(default=1, verbose_name='https://i.imgur.com/ShzwUoR.png'),
            preserve_default=False,
        ),
    ]
