# Generated by Django 4.0.2 on 2022-02-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_comic_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='image',
            field=models.URLField(),
        ),
    ]
