# Generated by Django 4.0.2 on 2022-02-28 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_comic_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCollection',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('comicCollection', models.ManyToManyField(to='base.Comic')),
            ],
        ),
    ]
