# Generated by Django 4.0.2 on 2022-02-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_usercollection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercollection',
            name='comicCollection',
            field=models.ManyToManyField(blank=True, to='base.Comic'),
        ),
        migrations.AlterField(
            model_name='usercollection',
            name='userid',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
