# Generated by Django 4.0.2 on 2022-02-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_usercollection_comiccollection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercollection',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
