# Generated by Django 4.0.2 on 2022-02-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_usercollection_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercollection',
            name='name',
            field=models.CharField(default='defaultName', max_length=100),
        ),
    ]
